<?php
/*
 * Generated configuration file
 * Generated by: phpMyAdmin 4.7.4 setup script
 * Date: Thu, 16 Nov 2017 05:04:07 +0000
 */

/* Servers configuration */
$i = 0;

/* Server: 教室サーバー [1] */
$i++;
$cfg['Servers'][$i]['verbose'] = '教室サーバー';
$cfg['Servers'][$i]['host'] = '192.168.20.224';
$cfg['Servers'][$i]['port'] = '';
$cfg['Servers'][$i]['socket'] = '';
$cfg['Servers'][$i]['auth_type'] = 'cookie';
$cfg['Servers'][$i]['user'] = 'root';
$cfg['Servers'][$i]['password'] = 'high01';

/* End of servers configuration */

$cfg['blowfish_secret'] = 'Zl>;.D<f5E#<Y06!A<hy-IGoYJiL-=yn';
$cfg['DefaultLang'] = 'ja';
$cfg['ServerDefault'] = 1;
$cfg['UploadDir'] = '';
$cfg['SaveDir'] = '';
?>